services:
  reverse-proxy:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - web
      - server
    links:
      - "web:web"
      - "server:server"
  web:
    image: sehsyha/pinou-web:latest
    expose:
      - "80"

  server:
    image: sehsyha/pinou-server:latest
    expose:
      - "3000"
    environment:
      NODE_ENV: production
      DATABASE_HOST: "database"
    links:
      - "database:database"
    depends_on:
      - database

  database:
    image: 'mongo'
    container_name: 'database'
    environment:
      - MONGO_INITDB_DATABASE=pinou
    volumes:
      - ./data:/data/db
    ports:
      - '27017-27019:27017-27019'